//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantastics
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FantasticsEntities : DbContext
    {
        public FantasticsEntities()
            : base("name=FantasticsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<option> options { get; set; }
        public virtual DbSet<product_meta> product_meta { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<term_relationships> term_relationships { get; set; }
        public virtual DbSet<term_taxonomy> term_taxonomy { get; set; }
        public virtual DbSet<termmeta> termmetas { get; set; }
        public virtual DbSet<term> terms { get; set; }
        public virtual DbSet<usermeta> usermetas { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
