//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantastics
{
    using System;
    using System.Collections.Generic;
    
    public partial class option
    {
        public long option_id { get; set; }
        public string option_name { get; set; }
        public string option_value { get; set; }
        public string autoload { get; set; }
    }
}
