//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantastics
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_meta
    {
        public long meta_id { get; set; }
        public Nullable<long> product_id { get; set; }
        public string meta_key { get; set; }
        public string meta_value { get; set; }
    }
}
