//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantastics
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public long ID { get; set; }
        public string product_author { get; set; }
        public Nullable<System.DateTime> product_date { get; set; }
        public Nullable<System.DateTime> product_date_gmt { get; set; }
        public string product_description { get; set; }
        public string product_title { get; set; }
        public string product_excerpt { get; set; }
        public string product_status { get; set; }
        public string comment_status { get; set; }
        public string ping_status { get; set; }
        public string post_password { get; set; }
        public string product_name { get; set; }
        public string to_ping { get; set; }
        public string pinged { get; set; }
        public Nullable<System.DateTime> product_modified { get; set; }
        public Nullable<System.DateTime> product_modified_gmt { get; set; }
        public string product_content_filtered { get; set; }
        public Nullable<long> product_parent { get; set; }
        public string guid { get; set; }
        public Nullable<int> menu_order { get; set; }
        public string product_type { get; set; }
        public string product_mime_type { get; set; }
        public Nullable<long> comment_count { get; set; }
    }
}
