//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantastics
{
    using System;
    using System.Collections.Generic;
    
    public partial class term_taxonomy
    {
        public long term_id { get; set; }
        public string taxonomy { get; set; }
        public string description { get; set; }
        public Nullable<long> parent { get; set; }
        public Nullable<long> count { get; set; }
    }
}
