//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantastics
{
    using System;
    using System.Collections.Generic;
    
    public partial class term
    {
        public long term_id { get; set; }
        public string name { get; set; }
        public string slug { get; set; }
        public Nullable<long> term_group { get; set; }
    }
}
