//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantastics
{
    using System;
    using System.Collections.Generic;
    
    public partial class term_relationships
    {
        public long object_id { get; set; }
        public long term_taxonomy_id { get; set; }
        public Nullable<int> term_order { get; set; }
    }
}
